server:
  port: 8888
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true
  application:
    name: web-admin
management:
  endpoints:
    web:
      exposure:
        include: '*'
